export const GETTING_FRIENDS = 'GETTING_FRIENDS';
export const GETTING_FRIENDS_SUCCESS = 'GETTING_FRIENDS_SUCCESS';
export const GETTING_FRIENDS_FAILURE = 'GETTING_FRIENDS_FAILURE';

export const ADDING_FRIEND = 'ADDING_FRIEND';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAILURE = 'ADD_FRIEND_FAILURE';

export const DELETING_FRIEND = 'DELETING_FRIEND';
export const DELETE_FRIEND_SUCCESS = 'DELETE_FRIEND_SUCCESS';
export const DELETE_FRIEND_FAILURE = 'DELETE_FRIEND_FAILURE';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';